/**
 * config/errorCodes.js — Centralized error codes for consistent client-side error handling
 * Allows frontend to intelligently handle different error scenarios
 */

'use strict';

const ERROR_CODES = {
  // Authentication Errors (AUTH_*)
  AUTH_INVALID: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_REVOKED: 'AUTH_003',
  AUTH_INSUFFICIENT_PERMS: 'AUTH_004',
  AUTH_ACCOUNT_LOCKED: 'AUTH_005',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_006',
  AUTH_API_KEY_MISSING: 'AUTH_007',
  AUTH_API_KEY_INVALID: 'AUTH_008',
  AUTH_MFA_REQUIRED: 'AUTH_009',
  AUTH_SESSION_EXPIRED: 'AUTH_010',

  // Validation Errors (VAL_*)
  VAL_EMAIL_INVALID: 'VAL_001',
  VAL_EMAIL_DUPLICATE: 'VAL_002',
  VAL_PASSWORD_WEAK: 'VAL_003',
  VAL_CONTENT_TYPE_INVALID: 'VAL_004',
  VAL_PAGINATION_INVALID: 'VAL_005',
  VAL_IDEMPOTENCY_KEY_MISSING: 'VAL_006',
  VAL_IDEMPOTENCY_KEY_INVALID: 'VAL_007',
  VAL_REQUEST_BODY_INVALID: 'VAL_008',
  VAL_SCHEMA_VALIDATION_FAILED: 'VAL_009',
  VAL_RATE_LIMIT_EXCEEDED: 'VAL_010',

  // Post Errors (POST_*)
  POST_NOT_FOUND: 'POST_001',
  POST_LOCKED: 'POST_002',
  POST_ALREADY_PUBLISHED: 'POST_003',
  POST_NOT_DRAFT: 'POST_004',
  POST_INVALID_STATUS: 'POST_005',
  POST_CREATION_FAILED: 'POST_006',
  POST_UPDATE_FAILED: 'POST_007',
  POST_DELETE_FAILED: 'POST_008',
  POST_PLATFORM_NOT_CONNECTED: 'POST_009',

  // Publishing Errors (PUB_*)
  PUB_FAILED: 'PUB_001',
  PUB_PARTIAL_FAILURE: 'PUB_002',
  PUB_PLATFORM_ERROR: 'PUB_003',
  PUB_RATE_LIMIT: 'PUB_004',
  PUB_TIMEOUT: 'PUB_005',
  PUB_INSUFFICIENT_PLAN: 'PUB_006',

  // Platform Connection Errors (PLAT_*)
  PLAT_NOT_CONNECTED: 'PLAT_001',
  PLAT_CONNECTION_FAILED: 'PLAT_002',
  PLAT_TOKEN_EXPIRED: 'PLAT_003',
  PLAT_TOKEN_INVALID: 'PLAT_004',
  PLAT_OAUTH_FAILED: 'PLAT_005',
  PLAT_NOT_AVAILABLE: 'PLAT_006',

  // AI Service Errors (AI_*)
  AI_ADAPT_FAILED: 'AI_001',
  AI_RATE_LIMIT: 'AI_002',
  AI_SERVICE_UNAVAILABLE: 'AI_003',
  AI_TIMEOUT: 'AI_004',
  AI_INVALID_INPUT: 'AI_005',

  // Resource Errors (RES_*)
  RES_NOT_FOUND: 'RES_001',
  RES_CONFLICT: 'RES_002',
  RES_FORBIDDEN: 'RES_003',
  RES_GONE: 'RES_004',
  RES_UNSUPPORTED_MEDIA_TYPE: 'RES_005',

  // Server Errors (SRV_*)
  SRV_INTERNAL_ERROR: 'SRV_001',
  SRV_SERVICE_UNAVAILABLE: 'SRV_002',
  SRV_DATABASE_ERROR: 'SRV_003',
  SRV_EXTERNAL_API_ERROR: 'SRV_004',
  SRV_TIMEOUT: 'SRV_005',

  // CORS & Security Errors (SEC_*)
  SEC_CORS_VIOLATION: 'SEC_001',
  SEC_CSRF_INVALID: 'SEC_002',
  SEC_CONTENT_POLICY_VIOLATION: 'SEC_003',

  // Plan/Billing Errors (PLAN_*)
  PLAN_UPGRADE_REQUIRED: 'PLAN_001',
  PLAN_LIMIT_EXCEEDED: 'PLAN_002',
  PLAN_FEATURE_UNAVAILABLE: 'PLAN_003',
};

const ERROR_CODE_MAP = {
  // Status 400
  400: ERROR_CODES.VAL_REQUEST_BODY_INVALID,
  // Status 401
  401: ERROR_CODES.AUTH_INVALID,
  // Status 403
  403: ERROR_CODES.AUTH_INSUFFICIENT_PERMS,
  // Status 404
  404: ERROR_CODES.RES_NOT_FOUND,
  // Status 409
  409: ERROR_CODES.RES_CONFLICT,
  // Status 415
  415: ERROR_CODES.RES_UNSUPPORTED_MEDIA_TYPE,
  // Status 429
  429: ERROR_CODES.VAL_RATE_LIMIT_EXCEEDED,
  // Status 500
  500: ERROR_CODES.SRV_INTERNAL_ERROR,
  // Status 503
  503: ERROR_CODES.SRV_SERVICE_UNAVAILABLE,
};

const getErrorCode = (statusCode, _context) => {
  return ERROR_CODE_MAP[statusCode] || ERROR_CODES.SRV_INTERNAL_ERROR;
};

module.exports = { ERROR_CODES, ERROR_CODE_MAP, getErrorCode };
